/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_aicreate_mvc_handler_DeviceOperationHandler */

#ifndef _Included_cc_aicreate_mvc_handler_DeviceOperationHandler
#define _Included_cc_aicreate_mvc_handler_DeviceOperationHandler
#ifdef __cplusplus
extern "C" {
#endif
#undef cc_aicreate_mvc_handler_DeviceOperationHandler_INVOKE_RESULT_METHOD_INTERVAL
#define cc_aicreate_mvc_handler_DeviceOperationHandler_INVOKE_RESULT_METHOD_INTERVAL 500LL
/*
 * Class:     cc_aicreate_mvc_handler_DeviceOperationHandler
 * Method:    modifyMsg
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cc_aicreate_mvc_handler_DeviceOperationHandler_modifyMsg
  (JNIEnv *, jobject);

/*
 * Class:     cc_aicreate_mvc_handler_DeviceOperationHandler
 * Method:    doPreparing
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cc_aicreate_mvc_handler_DeviceOperationHandler_doPreparing
  (JNIEnv *, jobject);

/*
 * Class:     cc_aicreate_mvc_handler_DeviceOperationHandler
 * Method:    home
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cc_aicreate_mvc_handler_DeviceOperationHandler_home
  (JNIEnv *, jobject);

/*
 * Class:     cc_aicreate_mvc_handler_DeviceOperationHandler
 * Method:    dataRecord
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cc_aicreate_mvc_handler_DeviceOperationHandler_dataRecord
  (JNIEnv *, jobject);

/*
 * Class:     cc_aicreate_mvc_handler_DeviceOperationHandler
 * Method:    stopRecord
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cc_aicreate_mvc_handler_DeviceOperationHandler_stopRecord
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cc_aicreate_mvc_handler_DeviceOperationHandler
 * Method:    reshow
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cc_aicreate_mvc_handler_DeviceOperationHandler_reshow
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cc_aicreate_mvc_handler_DeviceOperationHandler
 * Method:    getReqult
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cc_aicreate_mvc_handler_DeviceOperationHandler_getReqult
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
